import { AlertTriangle, Clock } from "lucide-react";
import type { DataMeta } from "@/lib/market-data/types";
import { fmtDate } from "@/lib/format";

export function DataBadge({ meta }: { meta: DataMeta }) {
  if (meta.dataType === "simulated")
    return (
      <span className="inline-flex items-center gap-1.5 rounded-full bg-warn/15 px-2.5 py-1 text-xs font-semibold text-warn">
        <AlertTriangle size={12} /> SIMULATED DATA — not real market prices
      </span>
    );
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-line bg-surface-2 px-2.5 py-1 text-xs text-ink-2">
      <Clock size={12} />
      <span>
        Market data as of <span className="font-medium text-ink">{fmtDate(meta.asOf, true)}</span> · {meta.dataType === "delayed" ? "Delayed" : "Real-time"} ·{" "}
        {meta.provider === "yfinance"
          ? "Yahoo Finance (yfinance)"
          : meta.provider === "yfinance-snapshot"
            ? <>Yahoo Finance (yfinance) snapshot, refreshed {fmtDate(meta.retrievedAt, true)}</>
            : meta.provider}
      </span>
    </span>
  );
}

export function SimulatedBanner() {
  return (
    <div className="flex items-start gap-3 rounded-xl border border-warn/40 bg-warn/10 px-4 py-3 text-sm">
      <AlertTriangle size={18} className="mt-0.5 shrink-0 text-warn" />
      <p>
        <span className="font-semibold">Simulated data mode.</span> Prices, option chains and history on this page are generated by a model for demonstration and do not reflect real market conditions. Do not use them for any trading decision.
      </p>
    </div>
  );
}

export function ModelTag({ children = "Model estimate" }: { children?: React.ReactNode }) {
  return <span className="inline-flex items-center rounded-md bg-model/10 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-model">{children}</span>;
}
