"use client";

import { ShieldAlert } from "lucide-react";
import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";

export const DISCLAIMER_TEXT =
  "OptionLens provides educational and analytical information based on user-provided assumptions and available market data. It does not provide personalized financial advice, investment recommendations, or guarantees of returns. Options involve significant risk and may result in loss of capital.";

const KEY = "optionlens.disclaimer.v1";

interface Ctx {
  acknowledged: boolean;
  /** Resolves true once the user has acknowledged (immediately if already done). */
  requireAck: () => Promise<boolean>;
}

const DisclaimerContext = createContext<Ctx>({ acknowledged: false, requireAck: async () => true });
export const useDisclaimer = () => useContext(DisclaimerContext);

export function DisclaimerProvider({ children }: { children: React.ReactNode }) {
  const [acknowledged, setAck] = useState(false);
  const [open, setOpen] = useState(false);
  const [checked, setChecked] = useState(false);
  const resolver = useRef<((v: boolean) => void) | null>(null);

  useEffect(() => {
    try {
      setAck(localStorage.getItem(KEY) === "yes");
    } catch {}
  }, []);

  const requireAck = useCallback(() => {
    if (acknowledged) return Promise.resolve(true);
    setOpen(true);
    return new Promise<boolean>((res) => (resolver.current = res));
  }, [acknowledged]);

  const close = (ok: boolean) => {
    if (ok) {
      setAck(true);
      try {
        localStorage.setItem(KEY, "yes");
      } catch {}
    }
    setOpen(false);
    resolver.current?.(ok);
    resolver.current = null;
  };

  return (
    <DisclaimerContext.Provider value={{ acknowledged, requireAck }}>
      {children}
      {open && (
        <div className="fixed inset-0 z-[60] overflow-y-auto bg-black/50 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="disc-title">
          <div className="flex min-h-full items-center justify-center p-4">
          <div className="card w-full max-w-lg animate-fade-up p-6 shadow-pop">
            <div className="mb-4 flex items-center gap-3">
              <div className="grid h-10 w-10 place-items-center rounded-xl bg-warn/10 text-warn">
                <ShieldAlert size={20} />
              </div>
              <h2 id="disc-title" className="text-lg font-semibold">Before you continue</h2>
            </div>
            <p className="text-sm leading-relaxed text-ink-2">{DISCLAIMER_TEXT}</p>
            <ul className="mt-4 space-y-1.5 text-sm text-ink-2">
              <li>• Strategy outputs are analytical scenarios generated by a model, not recommendations.</li>
              <li>• Probabilities are model estimates based on implied volatility, not predictions.</li>
              <li>• Market data may be delayed, incomplete, or simulated — the data source is always labelled.</li>
            </ul>
            <label className="mt-5 flex cursor-pointer items-start gap-3 rounded-xl border border-line bg-surface-2 p-3 text-sm">
              <input type="checkbox" className="mt-0.5 h-4 w-4 accent-[rgb(var(--accent))]" checked={checked} onChange={(e) => setChecked(e.target.checked)} />
              <span>I understand that OptionLens is for education and analysis only and does not provide financial advice.</span>
            </label>
            <div className="mt-5 flex justify-end gap-2">
              <button className="btn-ghost" onClick={() => close(false)}>Cancel</button>
              <button className="btn-primary" disabled={!checked} onClick={() => close(true)}>Acknowledge & continue</button>
            </div>
          </div>
          </div>
        </div>
      )}
    </DisclaimerContext.Provider>
  );
}
