// Reads the pre-built JSON snapshot published with the GitHub Pages edition
// (generated by market-data-service/snapshot.py on a schedule). Runs in the browser.

import { MarketDataError, type DataMeta, type HistoryBar, type MarketDataProvider, type Quote, type RawChain, type SearchResult } from "./types";

export interface SnapshotIndex {
  generatedAt: string;
  riskFree: { rate: number; source: string };
  tickers: { symbol: string; name: string; exchange?: string | null; price: number; change: number | null; changePercent: number | null }[];
  failed: string[];
}

interface StockFile {
  quote: Quote;
  history: HistoryBar[];
  expirations: string[];
  meta: DataMeta;
}

export class StaticSnapshotProvider implements MarketDataProvider {
  readonly id = "yfinance-snapshot";
  private index?: Promise<SnapshotIndex>;
  private stocks = new Map<string, Promise<StockFile>>();

  constructor(private base: string) {}

  private async get<T>(path: string, notFound: string): Promise<T> {
    let res: Response;
    try {
      res = await fetch(`${this.base}/data/${path}`, { cache: "no-cache" });
    } catch {
      throw new MarketDataError("Could not load market data. Check your connection and try again.", 503);
    }
    if (res.status === 404) throw new MarketDataError(notFound, 404);
    if (!res.ok) throw new MarketDataError(`Market data request failed (${res.status}).`, 502);
    return res.json() as Promise<T>;
  }

  getIndex(): Promise<SnapshotIndex> {
    if (!this.index) {
      this.index = this.get<SnapshotIndex>("index.json", "Market data snapshot not found.");
      this.index.catch(() => (this.index = undefined));
    }
    return this.index;
  }

  private async stock(symbol: string): Promise<StockFile> {
    const s = symbol.toUpperCase();
    if (!this.stocks.has(s)) {
      const idx = await this.getIndex();
      const covered = idx.tickers.map((t) => t.symbol);
      const p = this.get<StockFile>(
        `${encodeURIComponent(s)}/stock.json`,
        `“${s}” isn't covered by the GitHub Pages edition. Covered tickers: ${covered.join(", ")}.`,
      );
      p.catch(() => this.stocks.delete(s));
      this.stocks.set(s, p);
    }
    return this.stocks.get(s)!;
  }

  async search(q: string) {
    const idx = await this.getIndex();
    const needle = q.trim().toLowerCase();
    const data: SearchResult[] = idx.tickers
      .filter((t) => t.symbol.toLowerCase().startsWith(needle) || t.name.toLowerCase().includes(needle))
      .sort((a, b) => Number(!a.symbol.toLowerCase().startsWith(needle)) - Number(!b.symbol.toLowerCase().startsWith(needle)))
      .map((t) => ({ symbol: t.symbol, name: t.name, exchange: t.exchange ?? undefined, type: "EQUITY" }));
    return { data, meta: this.indexMeta(idx) };
  }

  async getQuote(symbol: string) {
    const s = await this.stock(symbol);
    return { data: s.quote, meta: s.meta };
  }

  async getQuotes(symbols: string[]) {
    const idx = await this.getIndex();
    const data = symbols.map((sym) => {
      const t = idx.tickers.find((x) => x.symbol === sym.toUpperCase());
      if (!t) return { symbol: sym.toUpperCase(), error: "not covered" };
      const q: Quote = {
        symbol: t.symbol,
        name: t.name,
        exchange: t.exchange,
        currency: "USD",
        price: t.price,
        previousClose: null,
        change: t.change,
        changePercent: t.changePercent,
        marketCap: null,
        averageVolume: null,
        volume: null,
        fiftyTwoWeekHigh: null,
        fiftyTwoWeekLow: null,
        dividendYield: 0,
      };
      return q;
    });
    return { data, meta: this.indexMeta(idx) };
  }

  async getHistory(symbol: string) {
    const s = await this.stock(symbol);
    return { data: s.history, meta: s.meta };
  }

  async getExpirations(symbol: string) {
    const s = await this.stock(symbol);
    return { data: s.expirations, meta: s.meta };
  }

  async getChain(symbol: string, expiration: string) {
    const s = await this.stock(symbol);
    const data = await this.get<RawChain>(`${encodeURIComponent(symbol.toUpperCase())}/chains/${expiration}.json`, `No option chain for ${symbol} ${expiration} in this snapshot.`);
    return { data, meta: s.meta };
  }

  async getRiskFreeRate() {
    return (await this.getIndex()).riskFree;
  }

  private indexMeta(idx: SnapshotIndex): DataMeta {
    return { provider: this.id, dataType: "delayed", asOf: idx.generatedAt, retrievedAt: idx.generatedAt };
  }
}
